FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
CMD [ "dotnet", "watch", "run", "--no-restore", "--urls", "http://0.0.0.0:5000" , "--verbosity", "normal"]

