version: '3.7'
services:
  web:
    image: b-api-dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - /Users/brianbrown/git/b-database:/data
      - ./api:/app/api
      - ./Controller:/app/Controller
      - ./AutoMapper:/app/AutoMapper
      - ./Repository:/app/Repository
      - ./Entity:/app/Entity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development