version: '3'
services:
  web:
    container_name: b-api-dev
    image: b-api-dev:latest
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - /Users/brianbrown/git/b-database:/data
      - ./Controller:/app/Controller
      - ./AutoMapper:/app/AutoMapper
      - ./Repository:/app/Repository
      - ./Entity:/app/Entity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development