name: Build and Publish Package

on: 
  push:
    branches:
    - master

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Dotnet Build and Publish
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.108'
    - name: Building Production Appsettings File
      run: echo '{"Weather":{"ServiceApiKey":"${{ secrets.WEATHER_SERVICE_API_KEY}}"}, "Maps":{"ServiceApiKey":"${{ secrets.MAP_SERVICE_API_KEY }}"}}' > appsettings.Production.json
    - run: dotnet build
    - run: dotnet publish -c Release
    - name: Deploy with rsync
      uses: maxheld83/rsync@v0.1.1
      env:
        HOST_FINGERPRINT: ${{ secrets.HOST_FINGERPRINT }}
        HOST_IP: ${{ secrets.HOST_IP }}
        HOST_NAME: ${{ secrets.HOST_NAME }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} 
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      with: 
        args: $GITHUB_WORKSPACE/bin/Release/netcoreapp2.2/publish/ ${{ secrets.HOST_USER }}@$HOST_NAME:${{ secrets.DEPLOY_PATH }} --exclude /resources
    - name: Restart service
      uses: maddox/actions/ssh@master
      env:
        HOST: ${{ secrets.HOST_IP }}
        USER: ${{ secrets.HOST_USER }}
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} 
      with: 
        args: sudo systemctl restart kestrel-budgetapi.service



