name: Build and Publish Package

on: 
  push:
    branches:
    - master

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Dotnet Build and Publish
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.108'
    - run: dotnet build
    - run: dotnet publish -c Release
    - name: sqlite
      run: sqlite3 --version